### ISSUE TITLE
Wrong silver blocks

### ISSUE THREAD

**Issue by ColossalPercy** [Gamertech/ChaoticProgression#10]
**Pack Version**
v1.0.7

**Describe the bug**
Unable to craft the FunOres Silver block from the FunOres Silver Ingot. You get the Ice and Fire Silver block instead which cannot be used in the neutronium compressor to make Silver Singularities

**Expected behavior**
Should craft FunOres Silver Block not Ice and Fire Silver Block. Or the Ice and Fire Silver block should be oreDict to `blockSilver` in order to work in the neutronium compressor.

**Comment by GamertechAU** [comment]
Can't reproduce this in 1.0.7. I've tried all crafting containers and FunOres silver ingots form the FunOres silver block as intended.

**Comment by ColossalPercy** [comment]
Apologies, reset the pack and it was working.
