### ISSUE TITLE
maybe im being stupid but i cant make a cauldren

### ISSUE THREAD

**Issue by memelordOG** [Gamertech/ChaoticProgression#11]
Hello, I am playing through the modpack and I have just currently made it to the stage 1 and in order to wash gems I need to make a cauldron and wash them in it.
I went to go make a cauldron and the crafting item did not show up.
so I went and started searching in the crafting lists and I have not been able to find a recipe for a cauldron.

I do not know if this is purposeful or not but I got extremely confused.  
thank you for your time!

**Comment by GamertechAU** [comment]
It's intended. Unlock iron production and you'll be able to make it.

The cauldron's meant to be hidden until then but that feature seems to be broken atm.
