### ISSUE TITLE
Server crashes on startup ver. 1.0.12

### ISSUE THREAD

**Issue by DessertOverlord** [Gamertech/ChaoticProgression#12]
Pack Version: 1.0.12

Describe the bug: On starting the server with the included server files on the CurseForge page, it will begin to initialize and crash after roughly 30 seconds to 1 minute of operation time.

Steps to reproduce the bug:
Launch the server using the provided files for 1.0.12

Expected behavior Describe what should happen:
The console window should close without warning and produce a crash report in the appropriate folder.

Link to crash/log file if relevant: https://pastebin.com/5rAB5vkz

**Comment by GamertechAU** [comment]
hmm, Quantum Storage isn't agreeing with the Reborn Core update. Lemme build a fix.

**Comment by DessertOverlord** [comment]
I just got off of my computer and am now on mobile, but from what I can tell it is definitely a problem between those two as there is currently an open issue on Quantum Storage's Github with the same subject. Thanks for your time helping out, too.

**Comment by GamertechAU** [comment]
Server files are uploaded. Waiting on Curse to approve them.

**Comment by GamertechAU** [comment]
Files are approved (that was quick) so should be good to go now mate.

Cheers for the report :)
