### ISSUE TITLE
Uploading server to a Host

### ISSUE THREAD

**Issue by vTrekz** [Gamertech/ChaoticProgression#13]
I have successfully transfered the files through filezilla and I cannot launch the server without it telling me It cannot locate the custom.jar

I have tried launching the server on my computer and then copying the files over there and using the jar, but it only launches as a Vanilla server. Any ideas on how this can be fixed or what is happening?

Thanks

**Comment by vTrekz** [comment]
I'm using Melon Cube hosting service and they use The multicraft FTP file access

**Comment by Gamertech** [comment]
Did you figure it out?
