### ISSUE TITLE
no quest book or better questing mod in the pack

### ISSUE THREAD

**Issue by Drewsdf** [Gamertech/ChaoticProgression#14]
**Pack Version**
version 1.0.12a

**Describe the bug**
whenever I load into the game I don't have a book so then I go into controls to look for a button to toggle the quest screen but the mod is not even in controls

**Steps to reproduce the bug**
1. load Minecraft
2. click on controls
3. scroll down to non-existent better questing tab
4 see no better questing tab and not be able to do the quests

**Comment by Gamertech** [comment]
So you found the quest book then? It says the hotkey in chat every time you login to the world as well as on the pack description page.
