### ISSUE TITLE
Flint pickaxe recipe conflict

### ISSUE THREAD

**Issue by Devor27** [Gamertech/ChaoticProgression#15]
There seems to be a recipe conflict with the recent patch for flint pickaxes (and perhaps more)

Started new world, gathered some flint and sticks. Tried to craft flint pickaxe using NEI recipe, it fed the items into the table correctly, but produced no output. If I exited the workbench and re-entered, the flint and sticks could make a stone pickaxe, but it then showed as unknown item, need stage 0, and did not function to mine.

Recipe didn't work in vanilla crafting bench either.

**Comment by Devor27** [comment]
Version 1.1.0, just to be clear

Tested with Stone Rods instead of sticks, and the Flint Pickaxe recipe worked fine - but doesn't work for progression since I need the Flint Pickaxe to get the stone.

**Comment by GamertechAU** [comment]
Fixed it. Quark added a new "quality of life" tweak that wasn't in their changelog...
