### ISSUE TITLE
unable to craft steel gear

### ISSUE THREAD

**Issue by Benrok** [Gamertech/ChaoticProgression#16]
**Pack Version**
version 1.1.1

**Describe the bug**
unable to craft a steel gear (4 steel around 1 iron) but crafts boiler casing isnted

**Expected behavior**
should craft steel gear or provide way to change when conflicting recipe

**Comment by GamertechAU** [comment]
Can't replicate. Boiler casing recipe was adjusted before release to have the iron in top left slot.
Both recipes show as intended for me. Try restarting the pack.
