### ISSUE TITLE
Iron?

### ISSUE THREAD

**Issue by MaxAstro** [Gamertech/ChaoticProgression#17]
I need a bucket to set up the crystallizer to make iron, but I need iron to make a bucket...

The only thing the quest line says is that I might find iron if I explore.  I've made a shaft down to bedrock and wandered quite a ways along the surface and I can't seem to find any way to get iron.

**Comment by MaxAstro** [comment]
Update: Eventually I figured out that you can use the condenser without crystal fluid to make iron ore; perhaps the quest line should instruct you to do that instead of saying that the condenser requires crystal fluid to use?

**Comment by GamertechAU** [comment]
There's plenty of iron about on the surface sitting in chests. Just need to take it.

**Comment by MaxAstro** [comment]
I guess my luck just sucks.  I found three chests exploring ~eight hexes in each direction; one was a blacksmith chest that had no iron, one was an enviromental accumulator that had no iron, and the third was an environmental accumulator that was destroyed by a dragon before I could even find out what was in it...

**Comment by GamertechAU** [comment]
Try finding where the dragon came from.

**Comment by MaxAstro** [comment]
I will admit that stealing from the dragon's horde never occurred to me, because I am kinda terrified of dragons.

That said, I'm fine on iron now, using the condenser on stone worked fine.  Now I just need to set up a reliable source of rotten flesh, so... hardened stone mobtrap, I guess...?
