### ISSUE TITLE
I can't figure out how to use the combustion heater

### ISSUE THREAD

**Issue by issuecreator** [Gamertech/ChaoticProgression#18]
**Pack Version**
1.2.1

**Describe the bug**
I have researched the mod pack and the mod description of the stone combustion heater and it doesn't say how to use it except for how to make the multiblock. I don't know if I am being stupid or if it is a different error.

**Steps to reproduce the bug**
1. Create the stone combustion heater and stone casing.
2. Place the stone casing down and the combustion heater in it.
3. Go to this link and scroll down. https://ftbwiki.org/Wooden_Combustion_Heater#Usage
4. Replace the wooden planks with stone and the wooden button to a stone one according to the picture.

**Expected behavior**
I should be able to convert the gunpowder into blaze powder

 Please tell me what to do on this, it would be very helpful.

**Comment by GamertechAU** [comment]
The button material doesn't matter, it just needs any redstone signal, and the multiblock structure can be cobble too if you want.

When it's complete, the heater UI will say the multiblock is valid, then take the top block off, drop gunpowder into the hollow, cover it up again with cobble, make sure there's fuel in it and click the button.

If you have enough fuel stored, it will turn gunpowder into blaze powder with a bang sound.
