### ISSUE TITLE
Dupe/Delete bug with Genetics Reborn machines

### ISSUE THREAD

**Issue by GamertechAU** [Gamertech/ChaoticProgression#2]
**Pack Version**
1.0

**Describe the bug**
Shift-clicking items into a Genetics Reborn machine dupes the item and deletes a random item from your inventory

**Steps to reproduce the bug**
1. Place a GR machine
2. Shift-click an item into it
3. The item dupes and deletes something from your inventory

**Expected behavior**
The item shouldn't dupe and shift-click as normal

**Link to crash/log file if relevant**
N/A

**Comment by captainbritian** [comment]
update to this it still works but doesnt delete random item from inventory this time
