### ISSUE TITLE
Can't craft Chiseled Demonstone Bricks

### ISSUE THREAD

**Issue by ColossalPercy** [Gamertech/ChaoticProgression#3]
**Pack Version**
v1.0

**Describe the bug**
Trying to craft the Enchantment Reallocator from LightningCraft but cannot make the Chiseled Demonstone Bricks. Crafting two Demonstone Brick Slabs together creates Demonstone Bricks instead, even though JEI says otherwise. Can no longer use the chisel to convert types either.

**Steps to reproduce the bug**
1. Craft two Demonstone Brick Slabs on top of each other
2. Get wrong Demonstone 

**Expected behavior**
Should get Chiseled Demonstone Bricks from craft

**Comment by ColossalPercy** [comment]
Apologies, it's the same for the understone chiseled bricks.

**Comment by GamertechAU** [comment]
LightningCraft's Chisel implementation was outdated, so I disabled it to prevent a crash.

The slab recipes were hardcoded into the mod and resisted changes in CraftTweaker, so I removed the recs using the slabs and made them go through a furnace instead.

**Comment by GamertechAU** [comment]
Update is released and should be on the Twitch app soon.
