### ISSUE TITLE
advancements says blook not book 

### ISSUE THREAD

**Issue by captainbritian** [Gamertech/ChaoticProgression#4]
1.0.1

on the a little bit evil quest/advancements 
disenchanting when combining a blook and an enchanted item in a purifier, you can extract the enchantment to use elsewhere.

**Comment by captainbritian** [comment]
also if creepers blow up near ores they dont destroy the ore they just mine it for you

**Comment by GamertechAU** [comment]
It's meant to say Blook. It's an actual item. Also there's little choice about the ore if you want the miner to work unfortunately.
