### ISSUE TITLE
Server files contain mods updated plus their old version

### ISSUE THREAD

**Issue by jinkhya** [Gamertech/ChaoticProgression#7]
**Pack Version**
1.05

**Describe the bug**
Server files contain the old version of the mod + its updated version.
like : 
CraftTweaker2-1.12-4.1.10.jar
CraftTweaker2-1.12-4.1.11.jar
FTBLib-5.3.0.54.jar
FTBLib-5.3.0.56.jar
etc.

**Steps to reproduce the bug**
1. Go to mods folder in server files
2. you'll see duplicates with different versions

**Expected behavior**
only the latest version of the mod :)

**Link to crash/log file if relevant**
 Please upload to Pastebin

**Comment by GamertechAU** [comment]
I have zero idea what happened there. The old files are gone in my pre-zip folder, but they're back in the zip o.o

Fixed files have been uploaded, waiting for Curse to approve them.

**Comment by GamertechAU** [comment]
Files are available now

**Comment by jinkhya** [comment]
thank you !
